runtime: python27
api_version: 1
threadsafe: yes

handlers:
  # All files that can be compiled in angular. Luckily, they all have suffixes.
  - url: /(.*\.(css|html|ico|js|png|txt|jpg))
    static_files: dist/clemency/\1
    upload: dist/clemency/(.*\.(css|html|ico|js|png|txt|jpg))
  # Site root, plus anything else, like deep urls
  # Make this be secure, otherwise oauth redirect won't work if they want to us with http://
  - url: /.*
    static_files: dist/clemency/index.html
    secure: always
    upload: dist/clemency/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
  - .git/
  - .firebaserc